version: '3.8'

services:
  ai-service:
    build: ./fruit_veg_cnn
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    volumes:
       - ./fruit_veg_cnn:/app

  postgres:
    image: postgres:15
    container_name: smartcart-db
    environment:
      POSTGRES_DB: smartcart
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d smartcart"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: smartcart-redis
    ports:
      - "6379:6379"

  store-backend:
    build: ./store_backend
    ports:
      - "8080:8080"
    depends_on:
      ai-service:
        condition: service_started
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/smartcart
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  store-frontend:
    build: ./store_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - store-backend

volumes:
  postgres_data: